### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by j-convey** [j-convey/BankTextCategorizer#2]
Implement functions into gui.

**Comment by GonGuzman** [comment]
I downloaded your code to Windows and I am getting the following error messages. Did you get it to run in windows? Any advise?
```
c:\...> python main.py
Traceback (most recent call last):
  File "C:\...\BankTextCategorizer\GUI\main.py", line 7, in <module>
    from summary import SummaryTab
  File "C:\...\BankTextCategorizer\GUI\summary.py", line 3, in <module>
    from QtWebEngineWidgets import QWebEngineView
ModuleNotFoundError: No module named 'QtWebEngineWidgets'
```
